/**
 * NameGenerator
 * Generates random names with variations in format (titles, middle names, initials).
 *
 * Usage: NameGenerator.generate() -> "Dr. John A. Smith"
 */
export const NameGenerator = (function () {
  // Data Pools
  const titles = [
    "Mr.",
    "Mrs.",
    "Ms.",
    "Dr.",
    "Prof.",
    "Rev.",
    "Sgt.",
    "Cpt.",
    "Cmdr.",
    "Director",
    "Agent",
    "Officer",
    "Exec.",
    "Hon.",
    "Gov.",
    "Sen.",
    "Det.",
    "Insp.",
    "Judge",
    "Baron",
    "Count",
    "Duke",
    "Prince",
    "Bishop",
    "Pastor",
    "Rabbi",
    "Father",
    "Sister",
    "Doc",
    "Coach",
    "Boss",
    "Lt.",
    "Col.",
    "Gen.",
    "Maj.",
    "Cpl.",
    "Chief",
    "Sheriff",
  ];

  const firstNames = [
    "James",
    "Mary",
    "John",
    "Patricia",
    "Robert",
    "Jennifer",
    "Michael",
    "Linda",
    "William",
    "Elizabeth",
    "David",
    "Barbara",
    "Richard",
    "Susan",
    "Joseph",
    "Jessica",
    "Thomas",
    "Sarah",
    "Charles",
    "Karen",
    "Christopher",
    "Nancy",
    "Daniel",
    "Lisa",
    "Matthew",
    "Betty",
    "Anthony",
    "Margaret",
    "Mark",
    "Sandra",
    "Donald",
    "Ashley",
    "Steven",
    "Kimberly",
    "Paul",
    "Emily",
    "Andrew",
    "Donna",
    "Joshua",
    "Michelle",
    "Kenneth",
    "Dorothy",
    "Kevin",
    "Carol",
    "Brian",
    "Amanda",
    "George",
    "Melissa",
    "Edward",
    "Deborah",
    "Ronald",
    "Stephanie",
    "Timothy",
    "Rebecca",
    "Jason",
    "Sharon",
    "Jeffrey",
    "Laura",
    "Ryan",
    "Cynthia",
    "Jacob",
    "Kathleen",
    "Gary",
    "Amy",
    "Nicholas",
    "Shirley",
    "Eric",
    "Angela",
    "Jonathan",
    "Helen",
    "Stephen",
    "Anna",
    "Larry",
    "Brenda",
    "Justin",
    "Pamela",
    "Scott",
    "Nicole",
    "Brandon",
    "Emma",
    "Benjamin",
    "Samantha",
    "Samuel",
    "Katherine",
    "Gregory",
    "Christine",
    "Frank",
    "Debra",
    "Alexander",
    "Rachel",
    "Raymond",
    "Catherine",
    "Patrick",
    "Carolyn",
    "Jack",
    "Janet",
    "Dennis",
    "Ruth",
    "Jerry",
    "Maria",
    "Tyler",
    "Heather",
    "Aaron",
    "Diane",
    "Jose",
    "Virginia",
    "Adam",
    "Julie",
    "Henry",
    "Joyce",
    "Nathan",
    "Victoria",
    "Douglas",
    "Olivia",
    "Zachary",
    "Kelly",
    "Peter",
    "Christina",
    "Kyle",
    "Lauren",
    "Walter",
    "Joan",
    "Ethan",
    "Evelyn",
    "Jeremy",
    "Judith",
    "Harold",
    "Megan",
    "Keith",
    "Cheryl",
    "Christian",
    "Andrea",
    "Roger",
    "Hannah",
    "Noah",
    "Martha",
    "Gerald",
    "Jacqueline",
    "Carl",
    "Frances",
    "Terry",
    "Gloria",
    "Sean",
    "Ann",
    "Austin",
    "Teresa",
    "Arthur",
    "Kathryn",
    "Lawrence",
    "Sara",
    "Jesse",
    "Janice",
    "Dylan",
    "Jean",
    "Bryan",
    "Alice",
    "Joe",
    "Madison",
    "Jordan",
    "Doris",
    "Billy",
    "Abigail",
    "Bruce",
    "Julia",
    "Albert",
    "Judy",
    "Willie",
    "Grace",
    "Gabriel",
    "Denise",
    "Logan",
    "Amber",
    "Alan",
    "Marilyn",
    "Juan",
    "Beverly",
    "Wayne",
    "Danielle",
    "Roy",
    "Theresa",
    "Ralph",
    "Sophia",
    "Randy",
    "Marie",
    "Eugene",
    "Diana",
    "Vincent",
    "Brittany",
    "Russell",
    "Natalie",
    "Elijah",
    "Isabella",
    "Louis",
    "Charlotte",
    "Bobby",
    "Rose",
    "Philip",
    "Alexis",
    "Johnny",
    "Kayla",
    "Victor",
    "Lori",
    "Martin",
    "Tiffany",
    "Bradley",
    "Gladys",
    "Leo",
    "Phyllis",
    "Caleb",
    "Rita",
    "Owen",
    "Leslie",
    "Lucas",
    "Kaitlyn",
    "Molly",
    "Cameron",
    "Gina",
    "Newton",
    "Holly",
    "Trevor",
  ];

  const lastNames = [
    "Smith",
    "Johnson",
    "Williams",
    "Brown",
    "Jones",
    "Garcia",
    "Miller",
    "Davis",
    "Rodriguez",
    "Martinez",
    "Hernandez",
    "Lopez",
    "Gonzalez",
    "Wilson",
    "Anderson",
    "Thomas",
    "Taylor",
    "Moore",
    "Jackson",
    "Martin",
    "Lee",
    "Perez",
    "Thompson",
    "White",
    "Harris",
    "Sanchez",
    "Clark",
    "Ramirez",
    "Lewis",
    "Robinson",
    "Walker",
    "Young",
    "Allen",
    "King",
    "Wright",
    "Scott",
    "Torres",
    "Nguyen",
    "Hill",
    "Flores",
    "Green",
    "Adams",
    "Nelson",
    "Baker",
    "Hall",
    "Rivera",
    "Campbell",
    "Mitchell",
    "Carter",
    "Roberts",
    "Gomez",
    "Phillips",
    "Evans",
    "Turner",
    "Diaz",
    "Parker",
    "Cruz",
    "Edwards",
    "Collins",
    "Reyes",
    "Stewart",
    "Morris",
    "Morales",
    "Murphy",
    "Cook",
    "Rogers",
    "Gutierrez",
    "Ortiz",
    "Morgan",
    "Cooper",
    "Peterson",
    "Bailey",
    "Reed",
    "Kelly",
    "Howard",
    "Ramos",
    "Kim",
    "Cox",
    "Ward",
    "Richardson",
    "Watson",
    "Brooks",
    "Chavez",
    "Wood",
    "James",
    "Bennett",
    "Gray",
    "Mendoza",
    "Ruiz",
    "Hughes",
    "Price",
    "Alvarez",
    "Castillo",
    "Sanders",
    "Patel",
    "Myers",
    "Long",
    "Ross",
    "Foster",
    "Jimenez",
    "Powell",
    "Jenkins",
    "Perry",
    "Russell",
    "Sullivan",
    "Bell",
    "Coleman",
    "Butler",
    "Henderson",
    "Barnes",
    "Gonzales",
    "Fisher",
    "Vasquez",
    "Simmons",
    "Romero",
    "Jordan",
    "Patterson",
    "Alexander",
    "Hamilton",
    "Graham",
    "Reynolds",
    "Griffin",
    "Wallace",
    "Moreno",
    "West",
    "Cole",
    "Hayes",
    "Bryant",
    "Herrera",
    "Gibson",
    "Ellis",
    "Tran",
    "Medina",
    "Aguilar",
    "Stevens",
    "Murray",
    "Ford",
    "Castro",
    "Marshall",
    "Owens",
    "Harrison",
    "Fernandez",
    "McDonald",
    "Woods",
    "Washington",
    "Kennedy",
    "Wells",
    "Vargas",
    "Henry",
    "Chen",
    "Freeman",
    "Webb",
    "Tucker",
    "Guzman",
    "Burns",
    "Crawford",
    "Olson",
    "Simpson",
    "Porter",
    "Mason",
    "Hunter",
    "Gordon",
    "Mendez",
    "Silva",
    "Shaw",
    "Snyder",
    "Dixon",
    "Hunt",
    "Palmer",
    "Robertson",
    "Black",
    "Holmes",
    "Stone",
    "Meyer",
    "Boyd",
    "Mills",
    "Warren",
    "Fox",
    "Rose",
    "Rice",
    "Moreno",
    "Schmidt",
    "Patel",
    "Ferguson",
    "Nichols",
    "Stephens",
    "Gardner",
    "Payne",
    "Kelley",
    "Dunn",
    "Pierce",
    "Arnold",
    "Tran",
    "Spencer",
    "Peters",
    "Hawkins",
    "Grant",
    "Hansen",
    "Flores",
    "Vaughan",
    "Lawson",
    "Fields",
    "Carr",
    "Chapman",
    "Harvey",
    "Burton",
    "Stanley",
    "Little",
    "Welch",
    "Larson",
  ];

  // Helper to get random item from array
  function getRandom(arr) {
    return arr[Math.floor(Math.random() * arr.length)];
  }

  /**
   * Generates a random name string.
   *
   * Variations:
   * - Title (10% chance)
   * - First Last (50%)
   * - First Middle Last (20%)
   * - First M. Last (15%)
   * - First M. N. Last (10%)
   * - F. Middle Last (5%)
   */
  function generate() {
    let nameParts = [];

    // 1. Title (10% chance)
    if (Math.random() < 0.1) {
      nameParts.push(getRandom(titles));
    }

    const first = getRandom(firstNames);
    const last = getRandom(lastNames);
    const middle = getRandom(firstNames); // Reuse first names for middle
    const middle2 = getRandom(firstNames);

    // Determine pattern
    const patternRoll = Math.random();
    let mainName = "";

    if (patternRoll < 0.5) {
      // First Last
      mainName = `${first} ${last}`;
    } else if (patternRoll < 0.7) {
      // First Middle Last
      mainName = `${first} ${middle} ${last}`;
    } else if (patternRoll < 0.85) {
      // First M. Last
      mainName = `${first} ${middle[0]}. ${last}`;
    } else if (patternRoll < 0.95) {
      // First M. N. Last (Two middle initials)
      mainName = `${first} ${middle[0]}. ${middle2[0]}. ${last}`;
    } else {
      // F. Middle Last (First initial, full middle)
      mainName = `${first[0]}. ${middle} ${last}`;
    }

    nameParts.push(mainName);
    return nameParts.join(" ");
  }

  // Public API
  return {
    generate: generate,
  };
})();
